### ISSUE TITLE
Test/HTML/Tidy/Recursive test failure

### ISSUE THREAD

**Issue by szabgab** [szabgab/perl.org.il#8]
The following error stared to appear:

```
$ perl new_site_bin/update_site.pl --repo . --outdir ~/perl.org.il/www/
1..1
# /home/travis/perl.org.il/www/library.html (1:1) Warning: inserting missing 'title' element
not ok 1 - No errors
#   Failed test 'No errors'
#   at /home/travis/perl5/perlbrew/perls/5.26.2/lib/site_perl/5.26.2/Test/HTML/Tidy/Recursive.pm line 72.
#          got: '1'
#     expected: '0'
HTML::Template->output() : fatal error in loop output : HTML::Template::param() : attempt to set parameter 'cuser' with an array ref - parameter is not a TMPL_LOOP! at /home/travis/perl5/perlbrew/perls/5.26.2/lib/site_perl/5.26.2/HTML/Template.pm line 3340.
 at /home/travis/build/szabgab/perl.org.il/site/new_site_bin/main.pl line 83.
# Looks like you failed 1 test of 1.
```

https://travis-ci.org/szabgab/perl.org.il/builds/386994369

@shlomif

**Comment by shlomif** [comment]
On Fri, 01 Jun 2018 22:32:35 -0700
Gabor Szabo <notifications@github.com> wrote:

> The following error stared to appear:
> 
> ```
> $ perl new_site_bin/update_site.pl --repo . --outdir ~/perl.org.il/www/
> 1..1
> # /home/travis/perl.org.il/www/library.html (1:1) Warning: inserting missing
> 'title' element not ok 1 - No errors
> #   Failed test 'No errors'
> #
> at /home/travis/perl5/perlbrew/perls/5.26.2/lib/site_perl/5.26.2/Test/HTML/Tidy/Recursive.pm
> line 72. #          got: '1' #     expected: '0'
> HTML::Template->output() : fatal error in loop output :
> HTML::Template::param() : attempt to set parameter 'cuser' with an array ref
> - parameter is not a TMPL_LOOP!
> at /home/travis/perl5/perlbrew/perls/5.26.2/lib/site_perl/5.26.2/HTML/Template.pm
> line 3340.
> at /home/travis/build/szabgab/perl.org.il/site/new_site_bin/main.pl line 83.
> # Looks like you failed 1 test of 1. ```
> 
> https://travis-ci.org/szabgab/perl.org.il/builds/386994369
> 
> @shlomif 
> 

thanks, I'll investigate.

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
My Favourite FOSS - http://www.shlomifish.org/open-source/favourite/

XSLT is what Chuck Norris has nightmares of.
    — http://www.shlomifish.org/humour/bits/facts/XSLT/

Please reply to list if it's a mailing list post - http://shlom.in/reply .
